var GameBt = (function () {
    function GameBt(inLevel) {
        this.level = inLevel;
    }
    GameBt.prototype.setStateIdle = function () {
        this.level.fStartBt.inputEnabled = true;
        this.level.fAutoBt.inputEnabled = true;
        this.level.fDoubleLBt.inputEnabled = false;
        this.level.fDoubleRBt.inputEnabled = false;
        this.level.fSymbol01Bt.inputEnabled = true;
        this.level.fSymbol02Bt.inputEnabled = true;
        this.level.fSymbol03Bt.inputEnabled = true;
        this.level.fSymbol04Bt.inputEnabled = true;
        this.level.fSymbol05Bt.inputEnabled = true;
        this.level.fSymbol06Bt.inputEnabled = true;
        this.level.fSymbol07Bt.inputEnabled = true;
        this.level.fSymbol08Bt.inputEnabled = true;
        this.level.fStartBt.setFrames(0, 0, 1, 0);
        this.level.fAutoBt.setFrames(0, 0, 1, 0);
        this.level.fDoubleLBt.setFrames(2, 2, 2, 2);
        this.level.fDoubleRBt.setFrames(2, 2, 2, 2);
        this.level.fSymbol01Bt.setFrames(0, 0, 1, 0);
        this.level.fSymbol02Bt.setFrames(0, 0, 1, 0);
        this.level.fSymbol03Bt.setFrames(0, 0, 1, 0);
        this.level.fSymbol04Bt.setFrames(0, 0, 1, 0);
        this.level.fSymbol05Bt.setFrames(0, 0, 1, 0);
        this.level.fSymbol06Bt.setFrames(0, 0, 1, 0);
        this.level.fSymbol07Bt.setFrames(0, 0, 1, 0);
        this.level.fSymbol08Bt.setFrames(0, 0, 1, 0);
    };
    GameBt.prototype.setStateRollOrDouble = function () {
        this.level.fStartBt.inputEnabled = false;
        this.level.fAutoBt.inputEnabled = false;
        this.level.fDoubleLBt.inputEnabled = false;
        this.level.fDoubleRBt.inputEnabled = false;
        this.level.fSymbol01Bt.inputEnabled = false;
        this.level.fSymbol02Bt.inputEnabled = false;
        this.level.fSymbol03Bt.inputEnabled = false;
        this.level.fSymbol04Bt.inputEnabled = false;
        this.level.fSymbol05Bt.inputEnabled = false;
        this.level.fSymbol06Bt.inputEnabled = false;
        this.level.fSymbol07Bt.inputEnabled = false;
        this.level.fSymbol08Bt.inputEnabled = false;
        this.level.fStartBt.setFrames(2, 2, 2, 2);
        this.level.fAutoBt.setFrames(2, 2, 2, 2);
        this.level.fDoubleLBt.setFrames(2, 2, 2, 2);
        this.level.fDoubleRBt.setFrames(2, 2, 2, 2);
        this.level.fSymbol01Bt.setFrames(2, 2, 2, 2);
        this.level.fSymbol02Bt.setFrames(2, 2, 2, 2);
        this.level.fSymbol03Bt.setFrames(2, 2, 2, 2);
        this.level.fSymbol04Bt.setFrames(2, 2, 2, 2);
        this.level.fSymbol05Bt.setFrames(2, 2, 2, 2);
        this.level.fSymbol06Bt.setFrames(2, 2, 2, 2);
        this.level.fSymbol07Bt.setFrames(2, 2, 2, 2);
        this.level.fSymbol08Bt.setFrames(2, 2, 2, 2);
    };
    GameBt.prototype.setStateWin = function () {
        this.level.fStartBt.inputEnabled = true;
        this.level.fAutoBt.inputEnabled = true;
        this.level.fDoubleLBt.inputEnabled = true;
        this.level.fDoubleRBt.inputEnabled = true;
        this.level.fSymbol01Bt.inputEnabled = true;
        this.level.fSymbol02Bt.inputEnabled = true;
        this.level.fSymbol03Bt.inputEnabled = true;
        this.level.fSymbol04Bt.inputEnabled = true;
        this.level.fSymbol05Bt.inputEnabled = true;
        this.level.fSymbol06Bt.inputEnabled = true;
        this.level.fSymbol07Bt.inputEnabled = true;
        this.level.fSymbol08Bt.inputEnabled = true;
        this.level.fStartBt.setFrames(0, 0, 1, 0);
        this.level.fAutoBt.setFrames(0, 0, 1, 0);
        this.level.fDoubleLBt.setFrames(0, 0, 1, 0);
        this.level.fDoubleRBt.setFrames(0, 0, 1, 0);
        this.level.fSymbol01Bt.setFrames(0, 0, 1, 0);
        this.level.fSymbol02Bt.setFrames(0, 0, 1, 0);
        this.level.fSymbol03Bt.setFrames(0, 0, 1, 0);
        this.level.fSymbol04Bt.setFrames(0, 0, 1, 0);
        this.level.fSymbol05Bt.setFrames(0, 0, 1, 0);
        this.level.fSymbol06Bt.setFrames(0, 0, 1, 0);
        this.level.fSymbol07Bt.setFrames(0, 0, 1, 0);
        this.level.fSymbol08Bt.setFrames(0, 0, 1, 0);
    };
    return GameBt;
}());
